# Generated by Django 3.2.7 on 2021-12-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_enquiry_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='tablet_view',
            new_name='screenshot',
        ),
    ]
