# Generated by Django 3.2.7 on 2021-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_rename_tablet_view_website_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='abbrevation',
            field=models.CharField(default='chrmf', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
