# Generated by Django 3.2.7 on 2021-12-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_website_abbrevation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
    ]
