# Generated by Django 3.2.7 on 2021-12-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rename_abbrevation_website_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='cool_aspect',
            field=models.URLField(default='https://i.imgur.com/bBA2Fuk.png'),
            preserve_default=False,
        ),
    ]
