# Generated by Django 3.2.7 on 2021-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_website_cool_aspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
