# Generated by Django 3.2.7 on 2021-12-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.category'),
        ),
        migrations.AddField(
            model_name='website',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='project_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='project_url',
            field=models.URLField(null=True),
        ),
    ]
