# Generated by Django 3.2.7 on 2021-12-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20211205_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='link',
        ),
    ]
